### ISSUE TITLE
six fisheye camera

### ISSUE THREAD

**Issue by guihui123** [facebook/Surround360#121]
Hi,fbriggs,we have used six 180 fisheye lens bulided a stereo panoramic camera and get reasonable result.After rectification  projection and cropping,we get six picture which have  horizontal view angle 150 and vertical view angle 180. And according to the formula i = r * sin( FOV/2 - 360 / n),we set left eye and right eye have a distance 4.0 (the radius of camera is 8.7).But it also has some tough question we can’t solve out.
First,in the bottom and top of panoramic video,pixels is unstable,some area is varying all the time.(In the middle of picture,i and my friend is walking around camera)So do you have more sample data,we want transform your data into a video compare with our video.
Second,the stitching result is not ideal when we close to camera.Our face have different degrees  distortion when distance between us and camera is less than 2 meter.But in your test data,the stitching result seems perfect.So why this happened and what improvement can we do?
Third,our  radius of camera is 8.7.So we must decrease eye distance limited to formula of I.It seems longer the radius of camera is,the bigger the  eye distance .So longer radius of camera must is good to result?
Thank you very much.

**Comment by fbriggs** [comment]
And according to the formula i = r * sin( FOV/2 - 360 / n),we set left eye and right eye have a distance 4.0 (the radius of camera is 8.7)
--->
It sounds like you have the following:
r = 8.7cm
FOV = 150
n = 6
So this gives i = 2.25. In order to get full 6.4cm distance between the two eyes, you need at least i > 3.2cm, so what you have now is not enough for full stereo.

we set left eye and right eye have a distance 4.0
-->
I'd like to double check about how you did that to make sure it is consistent my assumption. In batch_process_video.py line 45 there is --interpupilary_dist 6.4, which you could change to --interpupilary_dist 4.0. Alternatively, you could pass --interpupilary_dist 4.0 directly to TestRenderStereoPanorama. Did you do one of those?

First,in the bottom and top of panoramic video,pixels is unstable,some area is varying all the time.
-->
Our code has some ways to smooth the video out in time, but it may or may not be in effect depending on how you use it. If you are rendering using the GUI or directly with the script run_all.py, it automatically does that for you. If you are rendering by calling TestRenderStereoPanorama yourself, you must be careful about what parameters are passed in to get the benefit of temporal smoothing. Specifically the argument --prev_frame_data_dir tells TestRenderStereoPanorama to look for the data it needs for smoothing (which is the previous frame's input images to flow, and the previous frame's solution for flow). If you pass --prev_frame_data_dir NONE, it won't do any of that. I suggest getting the 2-frame sample dataset here (http://surround360.hacktv.xyz/sample/sample_dataset.zip), then following the README inside of that zip. It should explain how to use run_all.py. After using run_all.py, there is a directory named /vid with subdirctories for each frame, i.e. 000000, 000001, etc. Inside frame 000000 there are /000000/flow and /000000/flow_images. Those are the files that TestRenderStereoPanorama reads if you pass it the path to frame 000000 for --prev_frame_data_dir.

Second,the stitching result is not ideal when we close to camera.Our face have different degrees distortion when distance between us and camera is less than 2 meter.But in your test data,the stitching result seems perfect.So why this happened and what improvement can we do?
-->
It is a known issue with our system that results get distorted if things are too close to the camera. There are a few ways to improve:
(1) keep things far away from the camera
(2) add more cameras, but don't make the rig bigger (the idea is to have the cameras closer together, which makes optical flow easier).
(3) make sure your scene has enough light. Flow will have problems with darkness or noise.
(4) improve our code for optical flow

Third,our radius of camera is 8.7.So we must decrease eye distance limited to formula of I.It seems longer the radius of camera is,the bigger the eye distance .So longer radius of camera must is good to result?
--->
In order to increase the value of i, your options are:
(1) Increase horizontal FOV (you probably can't go any higher with your current system)
(2) Increase the number of cameras (I suggest at least 8 if you can)
(3) Increase the radius.

Increasing the radius might be the most practical option for you. However, the more you increase it, the harder it is for optical flow when things are close up, so you'd want to go to the minimum possible radius that gets you i = 3.2cm. Solving 3.2 = r * sin(150/2 - 360/6) ,we get r = 12.36cm. You should go a tiny bit higher than that to be safe, maybe 13cm.
