### ISSUE TITLE
exposure correction / blending error?

### ISSUE THREAD

**Issue by cvaldesmol** [facebook/Surround360#124]
I am running some test just with some frames and found out that in my scene the ceiling has issues (see ttached image)
<img width="1507" alt="exposure" src="https://cloud.githubusercontent.com/assets/6050772/19525563/5d221044-95ef-11e6-8ed4-5cdae6705898.png">
.
Is this an exposure correction / blending error ?
Please confirm if the software does any type of exposure correction or blending
What can you advice to improve the output?
I am using gopro
Thanks

**Comment by fbriggs** [comment]
There is blending, but if the two image colors are too different, the stitcher will transition from blending to picking one color (whichever it thinks is closer in the scene) in order to reduce ghosting. The seams you pointed out look like that is happening.

There may be some settings on the GoPro that help with this.

For the official Surround360 camera, we do very extensive color calibration to make it so the color is even across all cameras.

If you are using the python GUI (run_all.py), you can check "enable_render_coloradjust", and it will do some additional compensation.

**Comment by cvaldesmol** [comment]
You said " For the official Surround360 camera, we do very extensive color calibration to make it so the color is even across all cameras. "
How do you do it? how can I do the same for gopro?

**Comment by fbriggs** [comment]
First, we disable all automatic color correction on the camera hardware. It may or may not be possible to do that with GoPros, but you should turn auto-exposure/protune off if possible.

Second, we take pictures of a Macbeth Chart (https://en.wikipedia.org/wiki/ColorChecker) using D65 light. Using this data, we build color correction matrices that transform the original images to something more consistent. There is more than just color correction matrices, but that is a good start.
