### ISSUE TITLE
How fast have people gotten this to go from raw->video?

### ISSUE THREAD

**Issue by Qwerex** [facebook/Surround360#131]
Just an question for the devs/anyone trying this out, how fast have you guys gotten this to process each frame?

I want to see if it's possible to livestream VR with this and am wondering how fast this has the potential to be. Please list what settings you've used if anything.

Currently it's taking me over a minute to do isp->render->ffmpeg for 2 frames with the default configuration. Anyone know how to get that lower?

**Comment by fbriggs** [comment]
If you compile with Halide, it will reduce the time per frame for the ISP step from ~10 sec to ~1 sec. In our tests, the rest of the renderer usually takes about 30 seconds with top/bottom/pole removal enabled at 6k output resolution. You can get that down to much less (~5 sec) if you target a lower resolution (3k is good), and disable top/bottom cameras. Also note that the option --render_enable_color_autoadjust can add ~5 sec per frame at 6k, so if you already have consistent color between images, that should be disabled. It is also not recommended to use the --verbose option with GUI, since its text buffer gets slow.
