### ISSUE TITLE
GPU computation

### ISSUE THREAD

**Issue by guihui123** [facebook/Surround360#152]
Hi,fbriggs,we have porting all projection to NIVIDA GPU.And computational speeds seems having a huge improvement.But we are still bordered by the flow computation.
```
// sweep from bottom/right
				for (int y = (1 - stablerow)*(imgSize.height)-1; y >= stablerow*(imgSize.height); --y) {
					for (int x = imgSize.width - 1; x >= 0; --x) {
						if (alpha0.at<float>(y, x) > kUpdateAlphaThreshold && alpha1.at<float>(y, x) > kUpdateAlphaThreshold) {
							float currErr = errorFunction(I0, I1, alpha0, alpha1, I0x, I0y, I1x, I1y, x, y, flow, blurredFlow, flow.at<Point2f>(y, x));
							if (x < imgSize.width - 1)  { proposeFlowUpdate(alpha0, alpha1, I0, I1, I0x, I0y, I1x, I1y, flow, blurredFlow, currErr, x, y, flow.at<Point2f>(y, x + 1)); }
							if (y < imgSize.height - 1) { proposeFlowUpdate(alpha0, alpha1, I0, I1, I0x, I0y, I1x, I1y, flow, blurredFlow, currErr, x, y, flow.at<Point2f>(y + 1, x)); }
							flow.at<Point2f>(y, x) -= gradientStepSize * errorGradient(I0, I1, alpha0, alpha1, I0x, I0y, I1x, I1y, x, y, flow, blurredFlow, currErr);
						}
					}
				}
```
  the code shows the part of function patchMatchPropagationAndSearch which is the most time-consuming in flow computation.It seems the circulation can be divided into independent computation process.But all of the flow update is depend on the preceding computation.It make parallel computing bring a wrong result.So what can i do if i want to porting this part to NIVID GPU?

**Comment by fbriggs** [comment]
You are right that this code is not really parallelizable as is. However, it can be changed in a way that makes it more suitable for GPU implementation and still gets similar results. Instead of doing one sweep from top/left to bottom/right, and a second sweep from bottom/right to top/left, you do 4 sweeps:
1) left to right
2) top to bottom
3) right to left
4) bottom to top
In each of these 4 sweeps, the proposeFlowUpdate is called only on one neighbor instead of two.
In this setup, each sweep can be done with all rows or all columns in parallel.

On other thing to warn you about is that the render executes >=17 optical flow problems in parallel using CPU threads. If you test your GPU implementation in a single thread and see a speedup, that speedup may not hold in the multi-threading case. This is pretty tricky to fix. It might require considerable re-structuring of the code that calls flow.
