### ISSUE TITLE
video flicking

### ISSUE THREAD

**Issue by electech6** [facebook/Surround360#162]
I packed the 360 3D results of every frame  into a video (30fps). I try it in several different scenes, and I find that some regions (grassland, ground for example) in the final video are flicking. It  seems to be  related with the  optical flow calculation. Have you ever encountered this problem? Look forward to some effective solutions, thanks.

**Comment by fbriggs** [comment]
In order to determine what issue you are seeing, we will need to see some of the footage you are referring to. Also, please provide more detailed description of any commands or configuration through the GUI that you ran. I'm closing this task for now, but will re-open when you post this information.
