### ISSUE TITLE
GPU or CPU bound for render engine?

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#18]
Any recommendations on optimal hardware platform to drive the rendering software?
eg:
- GPU choice nVIDIA v. AMD ... CUDA v. OpenCL/OpenGL
- dual TITANs v. dual W9100s
- CPU choice i7 v, dual Xeon procs
- Bandwidth requirements for writing the 14 x USB RAW data streams to disk.

Thanks
Neil

**Comment by fbriggs** [comment]
The rendering software currently doesn't use GPU at all, so that is not a factor. It is multithreaded to take advantage of multiple CPU cores, and you will see a benefit up to ~20 CPUs. However, on a system with 20 CPUs it wouldn't use all of them all the time, so clock speed matters too.

I suggest a 16 CPU system with the highest clock speed you can get, the fastest RAM, and the fastest SSD storage.

You will need 16GB RAM minimum, but it is recommended to have 64GB or more.

We have rendered a lot of footage on MacPros with 6 CPU (hyperthreaded to 12 virtual cores), at 3.5Ghz, with 64GB of RAM, and 1TB internal SSDs. Anything above that would be good.
