### ISSUE TITLE
Is there any options to store RGB image sequences instead of .bin RAW file ?

### ISSUE THREAD

**Issue by nukbridge** [facebook/Surround360#190]
Help,

I'm testing our 8 PointGrey cameras and lenses with Camera Control software,

I need to check each images captured on same frame-time so want to store RGB image sequences directly without Unpacker.

Is there any options in Camera Control or where should I start to inspect sources ?

Thanks,

**Comment by aparrapo** [comment]
Hi @nukbridge, we do not save single images directly because of bandwidth restrictions (we would not have enough time to create and save those images in less than the max frame rate). However, if you are using less cameras and you have enough CPU/time bandwidth, you can modify the camera consumer in

https://github.com/facebook/Surround360/blob/master/surround360_camera_ctl_ui/source/CameraController.cpp#L457

to place the data wherever you want. You will need to add the code that takes the RAW frame and converts it to RGB, which can be found on the Unpacker.
