### ISSUE TITLE
FTHETA or RECTILINEAR

### ISSUE THREAD

**Issue by lm124757** [facebook/Surround360#210]
From the codes, I learned that surround360 supports both ftheta and rectilinear lens. From my understanding, ftheta lens may be more suitable for panorama since we need to project images to spherical coordinate and ftheta lens can produce more smooth resolution pictures. But this is just considered in theory and needs test. So what is your recommandation? Thanks.

**Comment by fbriggs** [comment]
I recommend using an f-theta lens, because otherwise it is hard to get a really large vertical FOV. The vertical FOV of the lenses on the side cameras in the ring determine how much of the panorama can be stereo, and how much must be mono supplied by the top and bottom cameras. Also, it is best if you can use the same type of lens for the top cameras as the side, and you want a fisheye lens for the top. So overall, I recommend trying to get an f-theta lens with min(horizontal FOV, vertical FOV) > 135.

**Comment by lm124757** [comment]
Thanks
