### ISSUE TITLE
Why not use white balance property setting on preview or capture time ?

### ISSUE THREAD

**Issue by nukbridge** [facebook/Surround360#216]
I think there's no 'White Balance' value settings on capture time in CameraControlUI, is this means all correction for color, white balance or others could be done with calibration and rendering pipe ?

How can I set same White Balance values for all cameras on capture time ? (such as PointGrey.cpp ?!)

Thanks,

**Comment by aparrapo** [comment]
Hi @nukbridge, that's correct, we don't have a white balance setting at this moment. During color calibration we set black level, white balance, color and correction matrix.

If you want yo use your own values, feel free to replace them on each ISP json file for each camera. However, I don't recommend doing so, since you're dealing with multiple cameras, and they should all see the same, and balancing more than 10 cameras by hand can take +3 hours.

It is true that the Point Grey cameras have their own auto white balance setting, but we don't use it for two reasons:

1) We capture RAW data, which is not supposed to have white point correction.
2) Since cameras in a 360 arrangement see different lighting, individually auto white balancing them will lead to inconsistent results in 360.

Thank you,
