### ISSUE TITLE
How to run generate stereo panorama from the sample data

### ISSUE THREAD

**Issue by jasjuang** [facebook/Surround360#36]
Can someone let me know the complete steps to generate stereo panorama from the sample data? There isn't a clear instruction in Readme.md on how to do this.

``````
./bin/TestRenderStereoPanorama --help
``````

Yields a lot of parameters and all has it's own default value and I have no idea which parameter is required for me to overwrite besides -imgs_dir and -output_data_dir.

``````
./bin/TestRenderStereoPanorama -imgs_dir ../sample_dataset/vid/000000/isp_out -output_data_dir ../sample_dataset/vid/000000/out
``````

shows

``````
E0805 15:27:22.046569  3968 SystemUtil.cpp:48] Terminated with VrCamException: missing required command line argument: src_intrinsic_param_file
``````

however there is no checkerboard images in the sample zip file for me to calibrate nor there is any files storing the intrinsic/extrinsic parameters.

**Comment by fbriggs** [comment]
You can find more detailed instructions in this manual:
https://github.com/facebook/Surround360/blob/master/surround360_design/assembly_guide/Surround360_Manual.pdf

This document includes instructions for both hardware and software use.

In general, I recommend running the higher level scripts rather than TestRenderStereoPanorama directly. To do so, cd to the /surround360_render directory, then run 'python scripts/run_all.py', and you should get a GUI to configure options. From this GUI, you can specify a list of steps to be run. You may wish to put in only the 'render' step instead of all of the other steps. Doing that will call TestRenderStereoPanorama.

Regarding the --src_intrinsic_param_file parameter, we provide a sample file in /surround360_render/res/config/sunex_intrinsic.xml

This is the appropriate file to use for Sunex lenses, which are the lenses on our official build. This is also the right file to use if you are testing on the sample dataset that we provided.

Thanks for grinding through the non-obvious parts of our system. Please open another issue if you have further questions.
