### ISSUE TITLE
USB 3.0 Expansion Cards  UE-1008 vs UE-1004

### ISSUE THREAD

**Issue by superedo73** [facebook/Surround360#44]
Hi,

in the manual I see 5 x UE-1004 cards are used.
Can you confirm we can use 3 x UE-1008 cards in place of 5 x UE-1004 without performance loss?

I am also considering an alternative setup, with the UE-1008 plugged directly in the PC, without an intermediate breakout usb3/fiber box, in this case 2xUE-1008 cards + 1 on-board USB3 port would be sufficient?

Thanks.

Enrico

**Comment by superdog8** [comment]
You have to use 5 cards , as those particular cards have bandwidth constraints and sticking more than 4 4 cameras in those cards will result in decrease in framerate. You can plug in the cards directly to the PC without problems, as long as you observe bandwidth limitations. You can't use all 8  USB ports on those cards due to limitations in the card design.
