### ISSUE TITLE
Placement of Surround360 - "safe zone" under the camera?

### ISSUE THREAD

**Issue by superedo73** [facebook/Surround360#46]
Hi,
I see the two suggested placement setups at 7.5a and 7.5b of documentation manual.

It seems from the comparison of the two solutions that the setup 7.5a, with only the breakout box and the UPS under the camera, will result in no post-production remove activity at all, due to the smart stitching from the two bottom cameras. Is it correct?

In affermative case, can you specify the exact size/location of the "safe zone" where we can place our equipment (angle, origin, etc. etc.)?

Thank you in advance,

Enrico

**Comment by fbriggs** [comment]
The "automatic pole removal" feature of the stitcher only removes the pole (part of the tripod). It does not remove things on the ground near the pole, such as the breakout box.  The connection from the camera to the breakout box consists of USB 3.0 cables, which have a maximum length of 5m. Because of this, it is very hard to put the breakout box somewhere completely hidden. So if you want that to be removed, there is still some post to do. I recommend putting the breakout box close to the tripod so it is completely contained in the monoscopic region of the image. Fixing mono in post is much easier than fixing stereo.
