### ISSUE TITLE
Alternative cameras .... 

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#52]
Just saw BC's comment on using alternative cameras to get around the single source GreyPoint bottleneck .... are we tied to USB 3 data feeds or could we use HDMI or SDI video streams?

The main problem I see in using alternatives to the GP camera is the amount of thought and detail you guys have put into the design of the 'flying saucer' form factor, stereo sweet spot, lenses and workflow to say nothing of the science underpinning your optical flow algorithm .... for ex-rocket scientists this is probably all very straight forward stuff but for us mere mortals working in production and post in LA, it's a bit beyond our pay-grade and skill set.

Any suggestions on what cameras we might want to take a look at assuming there's a slim chance we could figure out the hard stuff.

**Comment by fbriggs** [comment]
I don't have any specific recommended cameras, but I can give you a formula that can rule out certain configurations as "definitely not going to work":

i = r * sin(FOV/2 - 360/n)           (use degrees not radians)
where
r = radius of your camera rig in centimeters (from center to tip of lens)
FOV = horizontal FOV of the lens (after correcting barrel distortion. for example using the sunex lenses we have now, they are 90 before, and 77 after; as a rough rule of thumb, subtract 15%).
n = number of cameras

So whatever camera configuration you have in mind, plug it in to this formula. What you get out is a number for i, which is the half the IPD we can simulate for stereo. If i is less than 3.2cm, the design is not going to work.

Getting i > 3.2cm doesn't guarantee it will be good because there are lots of other design factors to consider, i.e. this can only tell you if something won't work, not that it will work. For example, you also need to make sure you have enough overlap between the top and side cameras (and the top/bottom cameras may use different lenses).

If you have a specific camera/lens configuration in mind, post it here and I can take a look.
