### ISSUE TITLE
Top/Bottom Covers too large for milling?

### ISSUE THREAD

**Issue by VRabbitHole** [facebook/Surround360#56]
Trying to get a quote on total costs for CNCing all the parts ... just got this email back from a company that does prototyping saying that the Top and Bottom Cover parts are too large to go through their CNC mills:

" ... Unfortunately, the parts listed below are too large for our current process.  Currently, machined parts are generally limited to a maximum part size of 10in x 7in x 3.75in deep (254mm X 177.8mm X 95.2mm).  Thinner parts in select materials are limited to 22in x 14in (559mm x 356mm). Turned parts are limited to 2.95 in (75mm) in diameter and 9.0 in (228mm) in length. 

    FB360_V1_29_A
    File: FB360_V1_29_A(2).STEP

    FB360_V1_30_A
    File: FB360_V1_30_A(2).STEP ... "

Did FB have the Top/Bottom Cover parts milled in-house or through an external CNC shop?

Has anyone else run into difficulties getting these two parts milled or is it just a question of shopping around?

**Comment by andrewcoward** [comment]
Thank you for your question.

We designed the shells so that they could be fabricated from sheet metal, and tack welded together.

Here are some close up photos of the components:
![shell welds](https://cloud.githubusercontent.com/assets/21043167/17708784/59b4f970-639b-11e6-9a7d-de32a428a332.jpg)

We used a local vendor for all of the machining and fabrication, and they are very familiar with these parts.  Nor Cal Metal Fabricators (Oakland, CA) ; (510) 833-7157; Contact: Michael Tran

Regards
