### ISSUE TITLE
how to calculate min distance to object?

### ISSUE THREAD

**Issue by EnriqueMVega** [facebook/Surround360#58]
I know the user guide shows the minimum recommended distance to objects so they look 3d and the 360 is good
How is this calculated?
I am thinking on doing some changes, so my r will be different
i = r * sin(FOV/2 - 360/n)
Is there a relation between the formula (an r) to the min distance to objects ?
can I assume the smaller the r the higher the quaility?

**Comment by fbriggs** [comment]
Sorry for the much delayed reply...

The minimum recommended distance (8 ft) isn't directly related to the formula i = r * sin(FOV/2 - 360/n). Instead, it comes from the fact that the closer objects are to the cameras, the larger the displacement that must be found in optical flow. Large displacement is a known issue that makes optical flow harder, and beyond a certain limit, it can't find a solution reliably. There is no hard threshold where it breaks, its more like, the closer you get, the lower the probability of success. From practical experience, we have seen that between 5 an 8 ft is a good rule of thumb for our camera configuration.

can I assume the smaller the r the higher the quaility?
-->
Yes. All other things being equal, if you reduce the radius of the rig (r), then it decreases the displacement in optical flow, and it tends to find good solutions more reliably. However, there are tradeoffs that come with reducing r. For example, whatever your configuration it must still satisfy i > 3.2cm in the formula i = r * sin(FOV/2 - 360/n). If you decrease r, you must increase either FOV or n to maintain the same value of i. Increasing FOV reduces pixels/degree (things look blurrier in VR), and increasing n (# cameras) increases the cost, weight, probability of failure, and heat issues. That being said, my personal opinion is that it is worth it to make some sacrifices in these other parameters in order to achieve a small r; we have seen some results that suggest this makes a big difference in the quality of optical flow results.
