### ISSUE TITLE
why cameras on the top and bottom?

### ISSUE THREAD

**Issue by EnriqueMVega** [facebook/Surround360#59]
Just wondering why you decide to add cameras on the top and bottom and not increase the vfov so it covers 194 per camera? 
Is it because of distorsion? or because creating 3D on the top and bottom is not possible?
How can we create 3d on the top and bottom?
Cheers

**Comment by fbriggs** [comment]
Increasing the FOV of the top and bottom lenses from 185 to 194 would not have any benefit, and would decrease the pixel density, making it blurrier.

Making the top and bottom 3D is not possible for stereo 360 video. The reason is that stereo video consists of pre-computing a texture to apply to a sphere (actually one for each eye), and applying that same texture regardless of the user's head direction. This trick works for the sides, but at the top and bottom you see the other side of the sphere, which is intended for the opposite head orientation, and the images are reversed for each eye.

To get full 3D in all directions, you need a different technology, like full lightfields.

Currently the side lenses we have now provide a 77 degree strip of 3D around the horizon. This strip can be wider without causing the problem I mentioned above, up to at least 140 degrees, by using a wider FOV lens on the side (and also a higher resolution sensor to maintain pixel density).
