### ISSUE TITLE
Any instructions for how to use the cubemap for Oculus Rift?

### ISSUE THREAD

**Issue by mimiaofandisp** [facebook/Surround360#85]

**Comment by fbriggs** [comment]
I don't think there is currently support for cubemaps in Oculus Video on Rift, although there may be through other software. On GearVR, Oculus Video can play sideloaded cubemaps. To do so, the filename of the video needs to end with _cubemap_TB.mp4. The Surround 360 rendering software can generate cubemaps in the appropriate format. To use it, in the run_all.py GUI, specify cubemap format = video, cubemap_width = 720, cubemap_height = 1024, and quality = 3k. This will cause it to generate cubemap frames in the /cube_frames folder. You will need to write your own ffmpeg command to convert these frames into a video. A good way to get started is to run the ffmpeg step of the pipeline through the GUI using the 'dry run' and 'verbose' options. This will print the ffmpeg command to generate an equirect video. You can modify that to use the contents of /cube_frames instead of /eqr_frames.
